# Generated by Django 3.0.2 on 2020-11-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userqa',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('question1', models.CharField(max_length=1024, null=True)),
                ('question2', models.CharField(max_length=1024, null=True)),
                ('question3', models.CharField(max_length=1024, null=True)),
                ('question4', models.CharField(max_length=1024, null=True)),
                ('question5', models.CharField(max_length=1024, null=True)),
                ('question6', models.CharField(max_length=1024, null=True)),
                ('question7', models.CharField(max_length=1024, null=True)),
                ('question8', models.CharField(max_length=1024, null=True)),
                ('question9', models.CharField(max_length=1024, null=True)),
                ('question10', models.CharField(max_length=1024, null=True)),
                ('answer1', models.CharField(max_length=1024, null=True)),
                ('answer2', models.CharField(max_length=1024, null=True)),
                ('answer3', models.CharField(max_length=1024, null=True)),
                ('answer4', models.CharField(max_length=1024, null=True)),
                ('answer5', models.CharField(max_length=1024, null=True)),
                ('answer6', models.CharField(max_length=1024, null=True)),
                ('answer7', models.CharField(max_length=1024, null=True)),
                ('answer8', models.CharField(max_length=1024, null=True)),
                ('answer9', models.CharField(max_length=1024, null=True)),
                ('answer10', models.CharField(max_length=1024, null=True)),
            ],
        ),
    ]
