# Generated by Django 3.0.2 on 2020-11-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crctanswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crctans1', models.CharField(max_length=1024)),
                ('crctans2', models.CharField(max_length=1024)),
                ('crctans3', models.CharField(max_length=1024)),
                ('crctans4', models.CharField(max_length=1024)),
                ('crctans5', models.CharField(max_length=1024)),
                ('crctans6', models.CharField(max_length=1024)),
                ('crctans7', models.CharField(max_length=1024)),
                ('crctans8', models.CharField(max_length=1024)),
                ('crctans9', models.CharField(max_length=1024)),
                ('crctans10', models.CharField(max_length=1024)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.userqa')),
            ],
        ),
    ]
