# Generated by Django 3.0.2 on 2020-11-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20201108_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctanswers',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='root.userqa'),
        ),
    ]
