# Generated by Django 3.0.2 on 2020-11-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20201108_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('visitor_email', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=1024)),
                ('visitor_score', models.CharField(max_length=1)),
                ('usermail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.userqa')),
            ],
        ),
    ]
